version: "3"

services:
  mysql:
    image: mysql:8.0.0
    container_name: goms-v2-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    env_file:
      - .env

  redis:
    image: redis
    container_name: goms-v2-redis
    ports:
      - "6379:6379"

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    image: kimgyeongsu/goms-server
    container_name: goms-v2-server
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    env_file:
      - .env