object DependenciesVersions {
    const val QUERYDSL = "5.0.0"
    const val MOCKK = "1.13.8"
    const val KOTEST_JUNIT = "5.4.2"
    const val KOTEST_EXTENSION = "1.1.2"
    const val KOTEST_ASSERTIONS = "5.4.2"
    const val SPRING_TRANSACTION = "5.3.11"
    const val JACKSON_CORE = "2.13.4"
    const val SPRING_TEST = "2.7.7"
    const val SERVLET_VERSION = "4.0.1"
    const val EMAIL = "2.6.7"
    const val AWS_STARTER = "2.2.6.RELEASE"
    const val REDIS_VERSION = "2.7.2"
    const val MARIA_DB_VERSION = "2.1.2"
    const val JWT_VERSION = "0.11.5"
    const val MAP_STRUCT_VERSION = "1.5.2.Final"
    const val GAUTH_VERSION = "v2.0.0"
    const val LOG_VERSION = "2.1.21"
    const val FCM_VERSION = "8.1.0"
}
