name: GOMS V2 CD
on:
  push:
    branches: [ "main" , "develop" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Remove existing YML File
        run: rm -f goms-infrastructure/src/main/resources/application.yml
        shell: bash
      - name: Make YML File
        run: |
          touch goms-infrastructure/src/main/resources/application.yml
          echo "${{ secrets.WEB_YML }}" > goms-infrastructure/src/main/resources/application.yml
        shell: bash
      - name: Build with Gradle
        run: ./gradlew --build-cache clean build
      - name: Deploy to Server
        uses: 8G4B/GSM-SV-Deploy@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          target_path: /home/ubuntu/GOMS-Server
          user: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
